site_name: backstage-python-app-1
site_description: 'Main documentation for the backstage-python-app-1'
repo_url: https://github.com/VamsiKrish82/backstage-python-app-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'